version: '3'

services:
# https://hub.docker.com/_/mongo
  mongo:
    image: mongo:5.0.8
    container_name: bur_mongo
    restart: always
    tty: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    
    volumes:
      - /src/mondodb/db:/data/db
    networks:
        - burgueses_network

# https://hub.docker.com/_/mongo-express
  mongo-express:
    image: mongo-express:0.54
    container_name: bur_mongo_express
    restart: always
    tty: true
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    
    networks:
        - burgueses_network

networks:
  burgueses_network:
    driver: bridge