version: '3'

services:
  db:
    image: mariadb:10.8
    command: --innodb-use-native-aio=0
    container_name: bur_mysql
    restart: always
    tty: true
    volumes:
      - ../db/mysql:/var/lib/mysql
      - ../db/backup:/backup
    environment:
      - MYSQL_DATABASE=BURGUESES
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - burgueses_network

  mysqladmin:
    image: phpmyadmin
    container_name: bur_phpmysqladmin
    restart: always
    tty: true
    depends_on:
      - db
    links:
      - db
    ports:
      - "3002:80"
    networks:
      - burgueses_network
    mongodb:
      image: mongodb:3.4.10
      container_name: bur_mongodb
      restart: always
      tty: true
      ports:
        - "22017:22017"
      networks:
        - burgueses_network

networks:
  burgueses_network:
    driver: bridge
